# Generated by Django 3.1.7 on 2021-03-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome cliente')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome Cliente')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
            ],
        ),
    ]
